version: 0.1

phases:
  install:
    commands:
      - npm install -g serverless
  pre_build:
    commands:
      - aws configure set s3.signature_version s3v4
      - aws s3 sync s3://$S3/${CODEBUILD_BUILD_ID%:*} .serverless
  build:
    commands:
      - sls deploy -s $STAGE

artifacts:
  files:
    - .serverless/*
  discard-paths: yes
